"""add_grade_tariff_course_to_student

Revision ID: 0042987a1260
Revises: 1328e7561bfe
Create Date: 2025-09-12 15:48:05.932933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0042987a1260'
down_revision = '1328e7561bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tariff', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('tariff')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
