"""add_exam_type_to_student_and_webinar

Revision ID: 0ad5a6c491fc
Revises: 83d1537a11c7
Create Date: 2025-09-03 20:16:54.266149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, String


# revision identifiers, used by Alembic.
revision = '0ad5a6c491fc'
down_revision = '83d1537a11c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонки как nullable
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_type', sa.String(length=10), nullable=True))
    
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_type', sa.String(length=10), nullable=True))
    
    # Затем обновляем все существующие записи
    student_table = table('student',
                         column('exam_type', String)
                         )
    
    webinar_table = table('webinar',
                          column('exam_type', String)
                          )
    
    op.execute(
        student_table.update().values(exam_type='ege')
    )
    
    op.execute(
        webinar_table.update().values(exam_type='ege')
    )
    
    # После этого делаем колонки not nullable
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('exam_type', nullable=False)

    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.alter_column('exam_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.drop_column('exam_type')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('exam_type')

    # ### end Alembic commands ###
