"""Add OGE parallel plans models

Revision ID: 2da7e599aaad
Revises: aaccf42aea82
Create Date: 2025-09-10 19:02:59.395482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da7e599aaad'
down_revision = 'aaccf42aea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oge_parallel_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('webinars_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oge_topic_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['oge_topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', name='uq_oge_topic_order_topic')
    )
    with op.batch_alter_table('oge_topic_order', schema=None) as batch_op:
        batch_op.create_index('idx_oge_topic_order', ['order_index', 'is_active'], unique=False)

    op.create_table('oge_parallel_plan_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('current_topic_id', sa.Integer(), nullable=True),
    sa.Column('current_topic_position', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['current_topic_id'], ['oge_topic.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['oge_parallel_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'slot_number', name='uq_oge_parallel_plan_slot')
    )
    op.create_table('oge_parallel_plan_webinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('position_in_topic', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['oge_parallel_plan.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['oge_topic.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'webinar_id', name='uq_oge_parallel_plan_webinar')
    )
    with op.batch_alter_table('oge_parallel_plan_webinar', schema=None) as batch_op:
        batch_op.create_index('idx_oge_parallel_plan_webinar', ['plan_id', 'week_number', 'slot_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_parallel_plan_webinar', schema=None) as batch_op:
        batch_op.drop_index('idx_oge_parallel_plan_webinar')

    op.drop_table('oge_parallel_plan_webinar')
    op.drop_table('oge_parallel_plan_slot')
    with op.batch_alter_table('oge_topic_order', schema=None) as batch_op:
        batch_op.drop_index('idx_oge_topic_order')

    op.drop_table('oge_topic_order')
    op.drop_table('oge_parallel_plan')
    # ### end Alembic commands ###
