"""add_oge_category_fields

Revision ID: 4962d3c7b814
Revises: b1c2d3e4f5a6
Create Date: 2025-09-09 00:34:04.047462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4962d3c7b814'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('initial_grade')
        batch_op.drop_column('target_grade')

    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_oge_part1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('for_oge_part2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('for_oge_hard', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.drop_column('for_oge_hard')
        batch_op.drop_column('for_oge_part2')
        batch_op.drop_column('for_oge_part1')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_grade', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('initial_grade', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
