"""Initial migration or model changes

Revision ID: 4eab2b09b773
Revises: 
Create Date: 2025-06-14 12:27:25.808597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eab2b09b773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('platform_id', sa.String(length=100), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('initial_score', sa.Integer(), nullable=True),
    sa.Column('needs_python_basics', sa.Boolean(), nullable=True),
    sa.Column('task_26_deferred', sa.Boolean(), nullable=True),
    sa.Column('task_27_deferred', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_platform_id'), ['platform_id'], unique=False)

    op.create_table('task_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('known_task_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_programming', sa.Boolean(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_excel', sa.Boolean(), nullable=True),
    sa.Column('homework_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('for_beginners', sa.Boolean(), nullable=True),
    sa.Column('for_basic', sa.Boolean(), nullable=True),
    sa.Column('for_advanced', sa.Boolean(), nullable=True),
    sa.Column('for_expert', sa.Boolean(), nullable=True),
    sa.Column('for_mocks', sa.Boolean(), nullable=True),
    sa.Column('for_practice', sa.Boolean(), nullable=True),
    sa.Column('for_minisnap', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_webinar_url')
    )
    op.create_table('planned_webinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plan.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watched_webinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar_task_association',
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('task_number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_number_id'], ['task_number.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('webinar_id', 'task_number_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinar_task_association')
    op.drop_table('webinar_task')
    op.drop_table('webinar_comment')
    op.drop_table('watched_webinar')
    op.drop_table('planned_webinar')
    op.drop_table('webinar')
    op.drop_table('study_plan')
    op.drop_table('known_task_number')
    op.drop_table('users')
    op.drop_table('task_number')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_platform_id'))
        batch_op.drop_index(batch_op.f('ix_student_last_name'))
        batch_op.drop_index(batch_op.f('ix_student_first_name'))

    op.drop_table('student')
    # ### end Alembic commands ###
