"""Add design fields and notification images support

Revision ID: 6ce80528e3f0
Revises: 3840f3c0024a
Create Date: 2025-09-09 01:39:04.407137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce80528e3f0'
down_revision = '3840f3c0024a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_notification_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['update_notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('text_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('icon')
        batch_op.drop_column('text_color')
        batch_op.drop_column('background_color')

    op.drop_table('update_notification_image')
    # ### end Alembic commands ###
