"""Add is_excel to Webinar model

Revision ID: 79b2fd262de6
Revises: 8549f1b6d40f
Create Date: 2025-04-10 13:03:16.309037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b2fd262de6'
down_revision = '8549f1b6d40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_excel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.drop_column('is_excel')

    # ### end Alembic commands ###
