"""Add academic_year to Student model

Revision ID: 83d1537a11c7
Revises: 87115fc31859
Create Date: 2025-07-02 23:44:43.091656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d1537a11c7'
down_revision = '87115fc31859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.Integer(), nullable=True))

    # Обновляем существующие записи, устанавливая academic_year = 2025
    op.execute("UPDATE student SET academic_year = 2025")

    # Устанавливаем ограничение NOT NULL после обновления данных
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('academic_year', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
