"""Add WebinarTask model

Revision ID: 8549f1b6d40f
Revises: 
Create Date: 2025-04-10 00:17:28.329520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8549f1b6d40f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinar_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinar_task')
    # ### end Alembic commands ###
