"""Add for_summer to Webinar

Revision ID: 87115fc31859
Revises: d9ceb610f0fd
Create Date: 2025-07-02 19:13:40.839843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87115fc31859'
down_revision = 'd9ceb610f0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_summer', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.drop_column('for_summer')

    # ### end Alembic commands ###
