"""Add per-plan OGE topic order

Revision ID: 87b96ebcdb00
Revises: 2da7e599aaad
Create Date: 2025-09-10 19:29:48.561550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b96ebcdb00'
down_revision = '2da7e599aaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oge_parallel_plan_topic_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['oge_parallel_plan.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['oge_topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'topic_id', name='uq_oge_plan_topic_order_topic')
    )
    with op.batch_alter_table('oge_parallel_plan_topic_order', schema=None) as batch_op:
        batch_op.create_index('idx_oge_plan_topic_order', ['plan_id', 'order_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_parallel_plan_topic_order', schema=None) as batch_op:
        batch_op.drop_index('idx_oge_plan_topic_order')

    op.drop_table('oge_parallel_plan_topic_order')
    # ### end Alembic commands ###
