"""Add hard prog support to OGE plans

Revision ID: a75b5e1e38c7
Revises: 87b96ebcdb00
Create Date: 2025-09-10 20:04:32.256470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75b5e1e38c7'
down_revision = '87b96ebcdb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_parallel_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hard_prog_webinars_per_week', sa.Integer(), nullable=True))
    
    # Обновляем существующие записи значением по умолчанию
    op.execute("UPDATE oge_parallel_plan SET hard_prog_webinars_per_week = 0 WHERE hard_prog_webinars_per_week IS NULL")
    
    # Делаем колонку NOT NULL
    with op.batch_alter_table('oge_parallel_plan', schema=None) as batch_op:
        batch_op.alter_column('hard_prog_webinars_per_week', nullable=False)

    with op.batch_alter_table('oge_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hard_prog', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_topic', schema=None) as batch_op:
        batch_op.drop_column('is_hard_prog')

    with op.batch_alter_table('oge_parallel_plan', schema=None) as batch_op:
        batch_op.drop_column('hard_prog_webinars_per_week')

    # ### end Alembic commands ###
