"""Add OGETopic model and webinar association

Revision ID: aaccf42aea82
Revises: 6ce80528e3f0
Create Date: 2025-09-10 17:44:49.024205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaccf42aea82'
down_revision = '6ce80528e3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oge_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_numbers_str', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webinar_oge_topic_association',
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('oge_topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oge_topic_id'], ['oge_topic.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinar.id'], ),
    sa.PrimaryKeyConstraint('webinar_id', 'oge_topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinar_oge_topic_association')
    op.drop_table('oge_topic')
    # ### end Alembic commands ###
