"""Rename role regular to organizational_curator and add educational_curator

Revision ID: b32f6d459ce9
Revises: 79b2fd262de6
Create Date: 2025-04-10 13:19:55.937132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32f6d459ce9'
down_revision = '79b2fd262de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
    # Обновляем старые значения роли
    op.execute("UPDATE \"user\" SET role = 'organizational_curator' WHERE role = 'regular'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
    # Возвращаем старые значения роли
    op.execute("UPDATE \"user\" SET role = 'regular' WHERE role = 'organizational_curator'")
