"""Allow null topic_id for hard webinars in OGE plans

Revision ID: c346167be5c9
Revises: e10aa5f81692
Create Date: 2025-09-12 13:36:25.345664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c346167be5c9'
down_revision = 'e10aa5f81692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_parallel_plan', schema=None) as batch_op:
        batch_op.alter_column('hard_prog_webinars_per_week',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('oge_parallel_plan_topic_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_oge_plan_topic_order'))

    with op.batch_alter_table('oge_parallel_plan_webinar', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_oge_parallel_plan_webinar'))

    with op.batch_alter_table('oge_topic_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_oge_topic_order'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_topic_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_oge_topic_order'), ['order_index', 'is_active'], unique=False)

    with op.batch_alter_table('oge_parallel_plan_webinar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_oge_parallel_plan_webinar'), ['plan_id', 'week_number', 'slot_number'], unique=False)
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('oge_parallel_plan_topic_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_oge_plan_topic_order'), ['plan_id', 'order_index'], unique=False)

    with op.batch_alter_table('oge_parallel_plan', schema=None) as batch_op:
        batch_op.alter_column('hard_prog_webinars_per_week',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
