"""Add academic_year to Webinar

Revision ID: d9ceb610f0fd
Revises: 4eab2b09b773
Create Date: 2025-07-02 18:53:15.958712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer


# revision identifiers, used by Alembic.
revision = 'd9ceb610f0fd'
down_revision = '4eab2b09b773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.Integer(), nullable=True))
    
    # Затем обновляем все существующие записи
    webinar_table = table('webinar',
                          column('academic_year', Integer)
                          )
    
    op.execute(
        webinar_table.update().values(academic_year=2025)
    )
    
    # После этого делаем колонку not nullable
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.alter_column('academic_year', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar', schema=None) as batch_op:
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
