"""add webinar counts per week to study plan

Revision ID: df8acec6785b
Revises: 0042987a1260
Create Date: 2025-09-12 21:31:14.426815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8acec6785b'
down_revision = '0042987a1260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beginner_webinars_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('basic_webinars_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('advanced_webinars_per_week', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.drop_column('advanced_webinars_per_week')
        batch_op.drop_column('basic_webinars_per_week')
        batch_op.drop_column('beginner_webinars_per_week')

    # ### end Alembic commands ###
