"""add_priority_to_oge_topic

Revision ID: e10aa5f81692
Revises: a75b5e1e38c7
Create Date: 2025-09-12 00:51:29.588432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10aa5f81692'
down_revision = 'a75b5e1e38c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oge_topic', schema=None) as batch_op:
        batch_op.drop_column('priority')
    # ### end Alembic commands ###
